/*
    Warframe Analytics - Phase 1 Database Schema
    Generated by Antigravity
*/

-- STEP 1: Create Schemas
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'wf_base')
BEGIN
    EXEC('CREATE SCHEMA [wf_base]')
END
GO

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'wf_user')
BEGIN
    EXEC('CREATE SCHEMA [wf_user]')
END
GO

-- STEP 2: Base Game Tables (wf_base)

-- wf_base.Weapons
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[wf_base].[Weapons]') AND type in (N'U'))
BEGIN
    CREATE TABLE [wf_base].[Weapons](
        [WeaponId] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
        [UniqueName] [nvarchar](200) NULL,
        [Name] [nvarchar](200) NULL,
        [Type] [nvarchar](50) NULL,
        [MasteryRank] [int] NULL,
        [Impact] [float] NULL,
        [Puncture] [float] NULL,
        [Slash] [float] NULL,
        [CritChance] [float] NULL,
        [CritMultiplier] [float] NULL,
        [StatusChance] [float] NULL,
        [FireRate] [float] NULL,
        [MagazineSize] [int] NULL,
        [ReloadTime] [float] NULL,
        [Multishot] [float] NULL,
        [RawJson] [nvarchar](max) NULL
    )
END
GO

-- wf_base.Warframes
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[wf_base].[Warframes]') AND type in (N'U'))
BEGIN
    CREATE TABLE [wf_base].[Warframes](
        [WarframeId] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
        [UniqueName] [nvarchar](200) NULL,
        [Name] [nvarchar](200) NULL,
        [Armor] [int] NULL,
        [Health] [int] NULL,
        [Shields] [int] NULL,
        [Energy] [int] NULL,
        [SprintSpeed] [float] NULL,
        [RawJson] [nvarchar](max) NULL
    )
END
GO

-- wf_base.Mods
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[wf_base].[Mods]') AND type in (N'U'))
BEGIN
    CREATE TABLE [wf_base].[Mods](
        [ModId] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
        [UniqueName] [nvarchar](200) NULL,
        [Name] [nvarchar](200) NULL,
        [ModType] [nvarchar](50) NULL,
        [Polarity] [nvarchar](20) NULL,
        [MaxRank] [int] NULL,
        [RawJson] [nvarchar](max) NULL
    )
END
GO

-- wf_base.Arcanes
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[wf_base].[Arcanes]') AND type in (N'U'))
BEGIN
    CREATE TABLE [wf_base].[Arcanes](
        [ArcaneId] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
        [UniqueName] [nvarchar](200) NULL,
        [Name] [nvarchar](200) NULL,
        [ItemType] [nvarchar](50) NULL,
        [MaxRank] [int] NULL,
        [RawJson] [nvarchar](max) NULL
    )
END
GO

-- STEP 3: User Build Tables (wf_user)

-- 3A: My Warframe Builds
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[wf_user].[MyFrames]') AND type in (N'U'))
BEGIN
    CREATE TABLE [wf_user].[MyFrames](
        [FrameBuildId] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
        [WarframeId] [int] NOT NULL,
        [BuildName] [nvarchar](100) NULL,
        [FormaCount] [int] DEFAULT 0,
        [FinalArmor] [float] NULL,
        [FinalHealth] [float] NULL,
        [FinalShields] [float] NULL,
        [FinalStrength] [float] NULL,
        [FinalRange] [float] NULL,
        [FinalDuration] [float] NULL,
        [FinalEfficiency] [float] NULL,
        [Notes] [nvarchar](255) NULL,
        [CreatedAt] [datetime2](7) DEFAULT SYSDATETIME(),
        CONSTRAINT [FK_MyFrames_Warframes] FOREIGN KEY([WarframeId])
        REFERENCES [wf_base].[Warframes] ([WarframeId])
    )
END
GO

-- 3B: My Weapon Builds (Primary, Secondary, Melee)

-- MyPrimaryWeapons
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[wf_user].[MyPrimaryWeapons]') AND type in (N'U'))
BEGIN
    CREATE TABLE [wf_user].[MyPrimaryWeapons](
        [WeaponBuildId] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
        [WeaponId] [int] NOT NULL,
        [BuildName] [nvarchar](100) NOT NULL,
        [FormaCount] [int] DEFAULT 0,
        [FinalTotalDamage] [float] NULL,
        [FinalImpactDamage] [float] NULL,
        [FinalPunctureDamage] [float] NULL,
        [FinalSlashDamage] [float] NULL,
        [FinalCritChance] [float] NULL,
        [FinalCritMultiplier] [float] NULL,
        [FinalStatusChance] [float] NULL,
        [FinalFireRate] [float] NULL,
        [FinalMagazineSize] [int] NULL,
        [FinalReloadTime] [float] NULL,
        [FinalMultishot] [float] NULL,
        [FinalPunchThrough] [float] NULL,
        [FinalBurstDPS] [float] NULL,
        [FinalSustainedDPS] [float] NULL,
        [Notes] [nvarchar](255) NULL,
        [CreatedAt] [datetime2](7) DEFAULT SYSDATETIME(),
        CONSTRAINT [FK_MyPrimaryWeapons_Weapons] FOREIGN KEY([WeaponId])
        REFERENCES [wf_base].[Weapons] ([WeaponId])
    )
END
GO

-- MySecondaryWeapons
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[wf_user].[MySecondaryWeapons]') AND type in (N'U'))
BEGIN
    CREATE TABLE [wf_user].[MySecondaryWeapons](
        [WeaponBuildId] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
        [WeaponId] [int] NOT NULL,
        [BuildName] [nvarchar](100) NOT NULL,
        [FormaCount] [int] DEFAULT 0,
        [FinalTotalDamage] [float] NULL,
        [FinalImpactDamage] [float] NULL,
        [FinalPunctureDamage] [float] NULL,
        [FinalSlashDamage] [float] NULL,
        [FinalCritChance] [float] NULL,
        [FinalCritMultiplier] [float] NULL,
        [FinalStatusChance] [float] NULL,
        [FinalFireRate] [float] NULL,
        [FinalMagazineSize] [int] NULL,
        [FinalReloadTime] [float] NULL,
        [FinalMultishot] [float] NULL,
        [FinalPunchThrough] [float] NULL,
        [FinalBurstDPS] [float] NULL,
        [FinalSustainedDPS] [float] NULL,
        [Notes] [nvarchar](255) NULL,
        [CreatedAt] [datetime2](7) DEFAULT SYSDATETIME(),
        CONSTRAINT [FK_MySecondaryWeapons_Weapons] FOREIGN KEY([WeaponId])
        REFERENCES [wf_base].[Weapons] ([WeaponId])
    )
END
GO

-- MyMeleeWeapons
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[wf_user].[MyMeleeWeapons]') AND type in (N'U'))
BEGIN
    CREATE TABLE [wf_user].[MyMeleeWeapons](
        [WeaponBuildId] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
        [WeaponId] [int] NOT NULL,
        [BuildName] [nvarchar](100) NOT NULL,
        [FormaCount] [int] DEFAULT 0,
        [FinalTotalDamage] [float] NULL,
        [FinalImpactDamage] [float] NULL,
        [FinalPunctureDamage] [float] NULL,
        [FinalSlashDamage] [float] NULL,
        [FinalCritChance] [float] NULL,
        [FinalCritMultiplier] [float] NULL,
        [FinalStatusChance] [float] NULL,
        [FinalFireRate] [float] NULL,
        [FinalMagazineSize] [int] NULL,
        [FinalReloadTime] [float] NULL,
        [FinalMultishot] [float] NULL,
        [FinalPunchThrough] [float] NULL,
        [FinalBurstDPS] [float] NULL,
        [FinalSustainedDPS] [float] NULL,
        [Notes] [nvarchar](255) NULL,
        [CreatedAt] [datetime2](7) DEFAULT SYSDATETIME(),
        CONSTRAINT [FK_MyMeleeWeapons_Weapons] FOREIGN KEY([WeaponId])
        REFERENCES [wf_base].[Weapons] ([WeaponId])
    )
END
GO

-- STEP 4: Weapon Arcane Link Tables

-- PrimaryWeaponArcanes
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[wf_user].[PrimaryWeaponArcanes]') AND type in (N'U'))
BEGIN
    CREATE TABLE [wf_user].[PrimaryWeaponArcanes](
        [PrimaryWeaponArcaneId] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
        [WeaponBuildId] [int] NOT NULL,
        [ArcaneId] [int] NOT NULL,
        [SlotIndex] [tinyint] NOT NULL,
        [Rank] [tinyint] NOT NULL,
        CONSTRAINT [FK_PrimaryWeaponArcanes_Build] FOREIGN KEY([WeaponBuildId])
        REFERENCES [wf_user].[MyPrimaryWeapons] ([WeaponBuildId]),
        CONSTRAINT [FK_PrimaryWeaponArcanes_Arcane] FOREIGN KEY([ArcaneId])
        REFERENCES [wf_base].[Arcanes] ([ArcaneId])
    )
END
GO

-- SecondaryWeaponArcanes
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[wf_user].[SecondaryWeaponArcanes]') AND type in (N'U'))
BEGIN
    CREATE TABLE [wf_user].[SecondaryWeaponArcanes](
        [SecondaryWeaponArcaneId] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
        [WeaponBuildId] [int] NOT NULL,
        [ArcaneId] [int] NOT NULL,
        [SlotIndex] [tinyint] NOT NULL,
        [Rank] [tinyint] NOT NULL,
        CONSTRAINT [FK_SecondaryWeaponArcanes_Build] FOREIGN KEY([WeaponBuildId])
        REFERENCES [wf_user].[MySecondaryWeapons] ([WeaponBuildId]),
        CONSTRAINT [FK_SecondaryWeaponArcanes_Arcane] FOREIGN KEY([ArcaneId])
        REFERENCES [wf_base].[Arcanes] ([ArcaneId])
    )
END
GO

-- MeleeWeaponArcanes
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[wf_user].[MeleeWeaponArcanes]') AND type in (N'U'))
BEGIN
    CREATE TABLE [wf_user].[MeleeWeaponArcanes](
        [MeleeWeaponArcaneId] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
        [WeaponBuildId] [int] NOT NULL,
        [ArcaneId] [int] NOT NULL,
        [SlotIndex] [tinyint] NOT NULL,
        [Rank] [tinyint] NOT NULL,
        CONSTRAINT [FK_MeleeWeaponArcanes_Build] FOREIGN KEY([WeaponBuildId])
        REFERENCES [wf_user].[MyMeleeWeapons] ([WeaponBuildId]),
        CONSTRAINT [FK_MeleeWeaponArcanes_Arcane] FOREIGN KEY([ArcaneId])
        REFERENCES [wf_base].[Arcanes] ([ArcaneId])
    )
END
GO

-- STEP 5: Companion & Parazon Builds

-- MyCompanions
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[wf_user].[MyCompanions]') AND type in (N'U'))
BEGIN
    CREATE TABLE [wf_user].[MyCompanions](
        [CompanionBuildId] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
        [CompanionBaseId] [int] NOT NULL, -- Placeholder FK
        [BuildName] [nvarchar](100) NULL,
        [Notes] [nvarchar](255) NULL,
        [CreatedAt] [datetime2](7) DEFAULT SYSDATETIME()
    )
END
GO

-- MyParazons
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[wf_user].[MyParazons]') AND type in (N'U'))
BEGIN
    CREATE TABLE [wf_user].[MyParazons](
        [ParazonBuildId] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
        [BuildName] [nvarchar](100) NULL,
        [Notes] [nvarchar](255) NULL,
        [CreatedAt] [datetime2](7) DEFAULT SYSDATETIME()
    )
END
GO

-- STEP 6: Loadouts

-- Loadouts
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[wf_user].[Loadouts]') AND type in (N'U'))
BEGIN
    CREATE TABLE [wf_user].[Loadouts](
        [LoadoutId] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
        [Name] [nvarchar](100) NOT NULL,
        [FrameBuildId] [int] NULL,
        [PrimaryBuildId] [int] NULL,
        [SecondaryBuildId] [int] NULL,
        [MeleeBuildId] [int] NULL,
        [CompanionBuildId] [int] NULL,
        [ParazonBuildId] [int] NULL,
        [FocusSchool] [nvarchar](50) NULL,
        [Notes] [nvarchar](255) NULL,
        [CreatedAt] [datetime2](7) DEFAULT SYSDATETIME(),
        
        CONSTRAINT [FK_Loadouts_Frame] FOREIGN KEY([FrameBuildId])
        REFERENCES [wf_user].[MyFrames] ([FrameBuildId]),
        
        CONSTRAINT [FK_Loadouts_Primary] FOREIGN KEY([PrimaryBuildId])
        REFERENCES [wf_user].[MyPrimaryWeapons] ([WeaponBuildId]),
        
        CONSTRAINT [FK_Loadouts_Secondary] FOREIGN KEY([SecondaryBuildId])
        REFERENCES [wf_user].[MySecondaryWeapons] ([WeaponBuildId]),
        
        CONSTRAINT [FK_Loadouts_Melee] FOREIGN KEY([MeleeBuildId])
        REFERENCES [wf_user].[MyMeleeWeapons] ([WeaponBuildId]),
        
        CONSTRAINT [FK_Loadouts_Companion] FOREIGN KEY([CompanionBuildId])
        REFERENCES [wf_user].[MyCompanions] ([CompanionBuildId]),
        
        CONSTRAINT [FK_Loadouts_Parazon] FOREIGN KEY([ParazonBuildId])
        REFERENCES [wf_user].[MyParazons] ([ParazonBuildId])
    )
END
GO
